apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tastecam-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: tastecam.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tastecam-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tastecam-frontend
                port:
                  number: 3000
